branches:
  only:
    - master

language: node_js

node_js:
  - "8"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm i
  - cd client && npm i
  - cd ..
  - truffle test

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    CURRENT_DIR=$PWD
    cd "$TRAVIS_BUILD_DIR"
    git clone https://github.com/dev-bootcamp-2019/final-project-aashutoshrathi.git
    cd client/contracts
    git add .
    git commit -m "Updated contracts"
    git push -f -q https://aashutoshrathi:$GITHUB_API_KEY@github.com/dev-bootcamp-2019/final-project-aashutoshrathi.git
    cd "$TRAVIS_BUILD_DIR"
  fi
